name: "Buildar o site"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar reposit√≥rio
      uses: actions/checkout@v2.4.0
    - name: Instalar nix
      uses: cachix/install-nix-action@v20
    - name: Autenticar no cachix
      uses: cachix/cachix-action@v12
      with:
        name: gelos-icmc
        authToken: '${{ secrets.CACHIX_KEY }}'
    - name: Executar 'nix build'
      run: nix build
